# Generated by Django 5.1.5 on 2025-01-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0002_alter_task_created_at_alter_task_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tag",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(blank=True, to="to_do.tag"),
        ),
    ]
